### ISSUE TITLE
mysql init idempotency

### ISSUE THREAD

**Issue by andrewdmcleod** [ktsakalozos/layered-hive-charm#2]
if hive is destroyed and redeployed with the same mysql instance:

unit-hive-1[10013]: 2016-02-11 12:43:57 INFO unit.hive/1.hadoop-relation-changed logger.go:40 Metastore connection URL:#011 jdbc:mysql://172.31.47.23:3306/hive
unit-hive-1[10013]: 2016-02-11 12:43:57 INFO unit.hive/1.hadoop-relation-changed logger.go:40 Metastore Connection Driver :#011 com.mysql.jdbc.Driver
unit-hive-1[10013]: 2016-02-11 12:43:57 INFO unit.hive/1.hadoop-relation-changed logger.go:40 Metastore connection User:#011 xiehahzoupaitoc
unit-hive-1[10013]: 2016-02-11 12:43:58 INFO unit.hive/1.hadoop-relation-changed logger.go:40 Starting metastore schema initialization to 0.14.0
unit-hive-1[10013]: 2016-02-11 12:43:58 INFO unit.hive/1.hadoop-relation-changed logger.go:40 Initialization script hive-schema-0.14.0.mysql.sql
unit-hive-1[10013]: 2016-02-11 12:43:58 INFO unit.hive/1.hadoop-relation-changed logger.go:40 /home/hive/.beeline/history (No such file or directory)
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40 Error: Duplicate key name 'PCS_STATS_IDX' (state=42000,code=1061)
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40 org.apache.hadoop.hive.metastore.HiveMetaException: Schema initialization FAILED! Metastore state would be inconsistent !!
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40 **\* schemaTool failed ***
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40 Traceback (most recent call last):
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-hive-1/charm/hooks/hadoop-relation-changed", line 18, in <module>
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40     main()
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/**init**.py", line 67, in main
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40     bus.dispatch()
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 405, in dispatch
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40     _invoke(other_handlers)
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 388, in _invoke
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40     handler.invoke()
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 269, in invoke
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40     self._action(*args)
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-hive-1/charm/reactive/hive.py", line 59, in start_hive
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40     hive.configure_hive(database)
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40   File "lib/charms/hive.py", line 106, in configure_hive
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40     utils.run_as('hive', 'schematool', '-initSchema', '-dbType', 'mysql')
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40   File "/usr/local/lib/python3.4/dist-packages/jujubigdata/utils.py", line 351, in run_as
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40     return run(['su', user, '-c', quoted], env=env, stdin=stdin)
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40     raise CalledProcessError(retcode, cmd)
unit-hive-1[10013]: 2016-02-11 12:43:59 INFO unit.hive/1.hadoop-relation-changed logger.go:40 subprocess.CalledProcessError: Command '['su', 'hive', '-c', "'schematool' '-initSchema' '-dbType' 'mysql'"]' returned non-zero exit status 1
unit-hive-1[10013]: 2016-02-11 12:43:59 ERROR juju.worker.uniter.operation runhook.go:107 hook "hadoop-relation-changed" failed: exit status 1

**Comment by andrewdmcleod** [comment]
if tl;dr : it shouldnt re-run the init script if its already been run.
